version: "1.0"
kind: step-type
metadata:
  name: configu
  version: 0.0.1
  title: Setup Configu CLI
  isPublic: true
  description: Install and configure Configu CLI.
  sources:
    - "https://github.com/configu/setup-cli-codefresh"
  stage: incubating
  maintainers:
    - name: Configu Dev
      email: dev@configu.com
  categories:
    - featured
  official: true
  tags: [configuration]
  icon:
    type: svg
    url: "https://app.configu.com/logo192.png"
    background: "#ffffff"
  examples:
    - description: Export configurations
      workflow:
        configu_export:
          title: Export configurations
          type: configu
          arguments:
            VAULT_ADDR: "${{VAULT_ADDR}}"
            VAULT_PATH: "${{VAULT_PATH}}"
            VAULT_AUTH_TOKEN: "${{VAULT_AUTH_TOKEN}}"
    - description: Client Certificate
      workflow:
        Vault_to_Env:
          title: Importing vault values
          type: vault
          arguments:
            VAULT_ADDR: "${{VAULT_ADDR}}"
            VAULT_PATH: "${{VAULT_PATH}}"
            VAULT_AUTH_TOKEN: "${{VAULT_AUTH_TOKEN}}"
            VAULT_CLIENT_CERT_BASE64: "${{VAULT_CLIENT_CERT_BASE64}}"
            VAULT_CLIENT_KEY_BASE64: "${{VAULT_CLIENT_KEY_BASE64}}"
    - description: Approle Authentication
      workflow:
        Vault_to_Env:
          title: Configu export
          type: configu
          arguments:
            VAULT_ADDR: "${{VAULT_ADDR}}"
            VAULT_PATH: "${{VAULT_PATH}}"
            VAULT_AUTH_METHOD: APPROLE
            APPROLE_ROLE_ID: "${{APPROLE_ROLE_ID}}"
            APPROLE_SECRET_ID: "${{APPROLE_SECRET_ID}}"
    - description: Retrieve Single Key
      workflow:
        Vault_to_Env:
          title: Importing vault values
          type: vault
          arguments:
            VAULT_ADDR: "${{VAULT_ADDR}}"
            VAULT_PATH: "${{VAULT_PATH}}"
            VAULT_AUTH_TOKEN: "${{VAULT_AUTH_TOKEN}}"
            VAULT_FIELD_NAME: some-key-name
    - description: Retrieve Multiple Paths
      workflow:
        Vault_to_Env:
          title: Importing vault values
          type: vault
          arguments:
            VAULT_ADDR: "${{VAULT_ADDR}}"
            VAULT_PATH: kv/firstpath;kv/secondpath
            VAULT_PATH_DELIMITER: ;
            VAULT_AUTH_TOKEN: "${{VAULT_AUTH_TOKEN}}"
    - description: Add Prefix to Variables
      workflow:
        Vault_to_Env:
          title: Importing vault values
          type: vault
          arguments:
            VAULT_ADDR: "${{VAULT_ADDR}}"
            VAULT_PATH: kv/firstpath;kv/secondpath
            VAULT_PATH_DELIMITER: ;
            VAULT_AUTH_TOKEN: "${{VAULT_AUTH_TOKEN}}"
            VAULT_VARIABLE_EXPORT_PREFIX: pre_
  created_at: "2020-06-17T18:29:14.076Z"
  updated_at: "2020-06-17T18:29:14.076Z"
  latest: true
  id: 5eea60faae31e667669be284
spec:
  arguments: |-
    {
        "definitions": {},
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "additionalProperties": false,
        "patterns": [],
        "required": [
          "VAULT_ADDR",
          "VAULT_PATH"
        ],
        "properties": {
            "VAULT_ADDR": {
                "type": "string",
                "description": "Vault server URI. Example: https://vault.testdomain.io:8200 (required)"
            },
            "VAULT_PATH": {
                "type": "string",
                "description": "Path to secrets in vault. Example: secret/codefreshsecret (required)"
            },
            "VAULT_PATH_DELIMITER": {
                "type": "string",
                "description": "Path delimiter to break up multiple paths in the VAULT_PATH value"
            },
            "VAULT_AUTH_METHOD": {
              "type": "string",
              "description": "Vault authentication method. Valid options: APPROLE or TOKEN"
            },
            "VAULT_AUTH_TOKEN": {
                "type": "string",
                "description": "Vault authentication token (required)"
            },
            "APPROLE_ROLE_ID": {
              "type": "string",
              "description": "Vault AppRole Role ID. Required if auth method is APPROLE"
            },
            "APPROLE_SECRET_ID": {
              "type": "string",
              "description": "Vault AppRole Secret ID. Required if auth method is APPROLE"
            },
            "VAULT_CLIENT_CERT_BASE64": {
                "type": "string",
                "description": "Base64 encoded client cerificate"
            },
            "VAULT_CLIENT_KEY_BASE64": {
                "type": "string",
                "description": "Base64 encoded client key"
            },
            "VAULT_FIELD_NAME": {
                "type": "string",
                "description": "Set this field to export a single value with the specified key"
            },
            "VAULT_VARIABLE_EXPORT_PREFIX": {
                "type": "string",
                "description": "Add a string prefix to the exported variable names of groups or single values"
            }
        }
    }
  steps:
    main:
      name: vault
      image: codefresh/vault
      environment:
        - "VAULT_ADDR=${{VAULT_ADDR}}"
        - "VAULT_PATH=${{VAULT_PATH}}"
        - "VAULT_PATH_DELIMITER=${{VAULT_PATH_DELIMITER}}"
        - "VAULT_AUTH_TOKEN=${{VAULT_AUTH_TOKEN}}"
        - "VAULT_CLIENT_CERT_BASE64=${{VAULT_CLIENT_CERT_BASE64}}"
        - "VAULT_CLIENT_KEY_BASE64=${{VAULT_CLIENT_KEY_BASE64}}"
        - "VAULT_AUTH_METHOD=${{VAULT_AUTH_METHOD}}"
        - "APPROLE_ROLE_ID=${{APPROLE_ROLE_ID}}"
        - "APPROLE_SECRET_ID=${{APPROLE_SECRET_ID}}"
        - "VAULT_FIELD_NAME=${{VAULT_FIELD_NAME}}"
        - "VAULT_VARIABLE_EXPORT_PREFIX=${{VAULT_VARIABLE_EXPORT_PREFIX}}"
