version: "1.0"
kind: step-type
metadata:
  name: configu
  version: 0.0.1
  title: Setup Configu CLI
  isPublic: true
  description: Install and configure Configu CLI.
  sources:
    - "https://github.com/configu/setup-cli-codefresh"
  stage: incubating
  maintainers:
    - name: Configu Dev
      email: dev@configu.com
  categories:
    - featured
  official: true
  tags: [configuration]
  icon:
    type: svg
    url: "https://raw.githubusercontent.com/configu/configu/main/assets/icon.svg"
    background: "#ffffff"
  examples:
    - description: Export configurations
      workflow:
        configu_export:
          title: Export configurations
          type: configu
          arguments:
            COMMANDS:
              - configu --version
              - configu eval --store 'configu' --set 'test/codefresh' --schema '/codefresh/volume/${{CF_REPO_NAME}}/.cfgu.json' | configu export
spec:
  arguments: |-
    {
      "definitions": {},
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "additionalProperties": false,
      "patterns": [],
      "required": [
        "COMMANDS",
      ],
      "properties": {
        "VERSION": {
          "type": "string",
          "description": "The version of Configu CLI to install. A value of `latest` will install the latest version of Configu CLI. Defaults to `latest`.",
          "default": "latest"
        },
        "COMMANDS": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Commands to execute. Example: https://vault.testdomain.io:8200. (required)"
        }
      }
    }
  stepsTemplate: |-
    main:
      name: configu
      image: configu/cli:[[.Arguments.VERSION]]
      commands:
      [[ range $arg := .Arguments.COMMANDS ]]
        - '[[ $arg ]]'
      [[- end ]]
  delimiters:
    left: "[["
    right: "]]"
